metadata:
  engine: 4.1
  version: 2.0
  author: Carter Pollan
  contact: carter.pollan@gmail.com

units:
  kx: cx
  ky: cy - 7
  px: cx - 7
  py: ky
  ledy: -cx/2 + 3
  feet_rad: 3.25
  feet_offset: 1
  case_thickness: 1.5
  case_offset: .05
  case_trrs: 4

points:
  zones:
    matrix:
      key:
        padding: cy + 1
        spread: cx
      anchor:
        rotate: 5
      columns:
        pinky:
          key:
            col_net: P3
        ring:
          key:
            splay: -5
            origin: [-12, -19]
            stagger: 10
            col_net: P4
        middle:
          key:
            stagger: 6
            col_net: P5
        index:
          key:
            stagger: -7
            col_net: P6
        inner:
          key:
            stagger: -2
            col_net: P7
      rows:
        bottom:
          row_net: P20
        home:
          row_net: P19
        top:
          row_net: P18
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [-7, -19]
      columns:
        near:
          key:
            col_net: P5
        home:
          key:
            spread: 0
            splay: -14.5
            origin: [0, -80]
            col_net: P6
        far: 
          key:
            spread: 0
            splay: -14.5
            origin: [0, -80]
            col_net: P7
      rows:
        thumb:
          row_net: P15
  rotate: -15

outlines:
  keys:
  - what: rectangle
    where: true
    size: [16.75, 16.75]
  board:
  - what: polygon
    operation: stack
    fillet: 3
    points:
    - ref: matrix_pinky_top
      shift: [-px, py]
    - ref: matrix_ring_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx*4/2 - 5, py]
    - ref: matrix_inner_bottom
      shift: [cx*4/2 - 5,-cy/2]
    - ref: thumbfan_far_thumb
      shift: [-px+4,px]
    - ref: thumbfan_far_thumb
      shift: [px, py]
    - ref: thumbfan_far_thumb
      shift: [px, -py]
    - ref: thumbfan_home_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_home_thumb
      shift: [-cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [-cy/2, -py]
    - ref: matrix_pinky_bottom
      shift: [-px, -py]
  faceplateKeys:
  - what: rectangle
    where: true
    size: [14,14]
  faceplateOutline:
  - what: polygon
    operation: stack
    fillet: 3
    points:
    - ref: matrix_pinky_top
      shift: [-px, py]
    - ref: matrix_ring_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [-cx/2, py]
    - ref: matrix_middle_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_top
      shift: [cx/2, py]
    - ref: matrix_inner_home
      shift: [cx/2, 0]
    - ref: matrix_inner_home
      shift: [cx*4/2 - 5,0]
    - ref: matrix_inner_bottom
      shift: [cx*4/2 - 5,-cy/2]
    - ref: thumbfan_far_thumb
      shift: [-px+4,px]
    - ref: thumbfan_far_thumb
      shift: [px, py]
    - ref: thumbfan_far_thumb
      shift: [px, -py]
    - ref: thumbfan_home_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_home_thumb
      shift: [-cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [cy/2, -py]
    - ref: thumbfan_near_thumb
      shift: [-cy/2, -py]
    - ref: matrix_pinky_bottom
      shift: [-px, -py]
  faceplate:
  - name: faceplateOutline
  - operation: subtract
    name: faceplateKeys
  microcontroller_cut_out:
  - what: polygon
    operation: stack
    fillet: 3
    points:
    - ref: matrix_inner_top
      shift: [cx*2, py*2]
    - ref: matrix_inner_top
      shift: [cx/2, py*2]
    - ref: matrix_inner_home
      shift: [cx/2, 0]
    - ref: matrix_inner_home
      shift: [cx*4/2 - 5,0]
  case_inner:
  - name: board
    expand: case_offset
  case_outer:
  - name: board
    expand: case_offset + case_thickness
  case_edge:
  - name: case_outer
  - -case_inner
  - -microcontroller_cut_out
  case_edge_full:
  - name: case_outer
  - -case_inner
  case_feet_one:
  - what: circle
    where:
    - ref: matrix_pinky_top
      shift: [-cx/2 + feet_offset,cy/2 - feet_offset]
    radius: feet_rad
  case_feet_two:
  - what: circle
    where:
    - ref: matrix_middle_top
      shift: [-cx/2 + feet_offset,cy/2 - feet_offset]
    radius: feet_rad
  case_feet_three:
  - what: circle
    where:
    - ref: matrix_inner_top
      shift: [cx*3/2 + feet_offset,cy/2 - feet_offset]
    radius: feet_rad
  case_feet_four:
  - what: circle
    where:
    - ref: thumbfan_far_thumb
      shift: [cx/2 - feet_offset,cx/2 - feet_offset]
    radius: feet_rad
  case_feet_five:
  - what: circle
    where:
    - ref: thumbfan_far_thumb
      shift: [cx/2 - feet_offset,-cx/2 + feet_offset]
    radius: feet_rad
  case_feet_six:
  - what: circle
    where:
    - ref: matrix_pinky_bottom
      shift: [-cx/2 + feet_offset,-cx/2 + feet_offset]
    radius: feet_rad
  case_outer_feet:
  - name: case_feet_one
  - +case_feet_two
  - +case_feet_three
  - +case_feet_four
  - +case_feet_five
  - +case_feet_six
  test:
  - name: faceplateOutline
  - operation: subtract
    name: keys

cases:
  case:
  - what: outline
    name: case_outer
    extrude: 2
  - what: outline
    name: case_edge
    extrude: 7.8
  - what: outline
    name: case_edge_full
    extrude: 5.7
  - what: outline
    name: case_outer_feet
    extrude: .5
    operation: subtract
  faceplate:
  - what: outline
    name: faceplate
    extrude: 1.5

pcbs:
  boardPcb:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: custom/footprints/choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          traces: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      diode:
        what: custom/footprints/diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [3, -(cy/2 - 1.2)]
          rotate: 0
      microcontroller:
        what: custom/footprints/promicro
        params:
          reversable_pins: 5
        where:
          ref: matrix_inner_top
          shift: [2*px - 2, -5.25]
      audio:
        what: custom/footprints/trrs
        params:
          A: "P2"
          B: "P21"
          C: "VCC"
          D: "GND"
          reverse: true
          symmetric: true
        where:
          ref: matrix_inner_home
          shift: [px*2 + 9, -9.5]
          rotate: -90
      rgb1:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: P10
          dout: rgb2
        where:
          ref: matrix_inner_home
          shift: [2.5*px, -15.5]
          rotate: 90
      rgb2:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: rgb2
          dout: rgb3
        where:
          ref: thumbfan_far_thumb
          shift: [6, -6]
      rgb3:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: rgb3
          dout: rgb4
        where:
          ref: thumbfan_near_thumb
          shift: [-6, -6]
      rgb4:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: rgb4
          dout: rgb5
        where:
          ref: matrix_middle_bottom
          shift: [-7, -30]
          rotate: -10
      rgb5:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: rgb5
          dout: rgb6
        where:
          ref: matrix_pinky_bottom
          shift: [-6, -6]
      rgb6:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: rgb6
          dout: rgb7
        where:
          ref: matrix_pinky_top
          shift: [7, 13]
          rotate: 20 + 180
      rgb7:
        what: custom/footprints/rgb
        params:
          reverse: true
          din: rgb7
          dout: P1
        where:
          ref: matrix_index_top
          shift: [-3, 12]
          rotate: -15 + 180
